# Name of your application. Used to uniquely configure containers.
service: max_reps

# Name of the container image (use your-user/app-name on external registries).
image: ghcr.io/jbarren/max-reps

# Deploy to these servers.
servers:
  web:
    hosts:
      - arra.local
    options:
      publish:
        - "3000:3000"
  # job:
  #   hosts:
  #     - arra.local
  #   cmd: bin/jobs

# Where you keep your container images.
registry:
  server: ghcr.io
  username: jbarren
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: max_reps-db

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
volumes:
  - "max_reps_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64

ssh:
  user: neu

accessories:
  db:
    image: postgres:17
    host: arra.local
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: max_reps
        POSTGRES_DB: max_reps_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
